//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DostiCardDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MerchantTable
    {
        public int ID { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string Password { get; set; }
        public string ContactNo { get; set; }
        public string Address { get; set; }
        public string ProfilePic { get; set; }
        public Nullable<int> StoreID { get; set; }
        public string Designation { get; set; }
    
        public virtual StoreTable StoreTable { get; set; }
    }
}
