//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DostiCardDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StoreTable()
        {
            this.CustomerTables = new HashSet<CustomerTable>();
            this.MerchantTables = new HashSet<MerchantTable>();
        }
    
        public int ID { get; set; }
        public string StoreName { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public int PointsLimit { get; set; }
        public int PercentageDiscount { get; set; }
        public int PaymentToGetOnePoint { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerTable> CustomerTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MerchantTable> MerchantTables { get; set; }
    }
}
